version: '2'

services:
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    system-miniature-example:
        build: .
        network_mode: "host"
        command: "/opt/opendlv.miniature/bin/opendlv-system-miniature-example --cid=${CID} --freq=1 --id=1"
